#!/usr/bin/env  ruby
# -*- mode:ruby; -*-

# just like ./put, but we send to a non-ssl server; want to make sure net/https is still
# the appropirate thing to send to.

require 'uri'
require 'net/https'

OPEN_TIMEOUT = 60 * 60 * 2
READ_TIMEOUT = 60 * 60 * 2

ADDRESS = URI.parse 'http://c3.ripple.fcla.edu/data'

if not ARGV[0]
  STDERR.puts  "Usage: #{$0} filename"
  exit 0
end

filename = ARGV[0]

io = open filename

http = Net::HTTP.new(ADDRESS.host, ADDRESS.port)
http.use_ssl = ADDRESS.scheme == 'https'
http.open_timeout = OPEN_TIMEOUT
http.read_timeout = READ_TIMEOUT

request = Net::HTTP::Put.new(ADDRESS.request_uri)
io.rewind if io.respond_to?('rewind')
request.body_stream = io
request.initialize_http_header("Content-Length" => File.stat(filename).size.to_s)
request.basic_auth(ADDRESS.user, ADDRESS.password) if ADDRESS.user or ADDRESS.password

response = http.request(request)
puts response.inspect

puts "status: #{response.code}"
puts response.body
